# Generated by Django 5.2.11 on 2026-02-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_requests', '0002_alter_deliveryrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
